services:
  - type: web
    name: nova-volleyball-checkin
    env: node
    plan: free
    buildCommand: npm install && npm run build && npm run build:server
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
